FROM golang:1.25-alpine AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/api ./cmd/api
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/scheduler ./cmd/scheduler

FROM alpine:3.22

RUN adduser -D -g '' appuser

WORKDIR /app

COPY --from=build /out/api /app/api
COPY --from=build /out/scheduler /app/scheduler

USER appuser

EXPOSE 8080

CMD ["/app/api"]
